CREATE TABLE STG_PRODUTO AS SELECT * FROM DIM_VENDA_PRODUTO WITH NO DATA;
CREATE TABLE STG_LOJA AS SELECT * FROM DIM_VENDA_LOJA WITH NO DATA;
CREATE TABLE STG_FUNCIONARIO AS SELECT * FROM DIM_VENDA_VENDEDOR WITH NO DATA;
CREATE TABLE STG_CLIENTE AS SELECT * FROM DIM_VENDA_CLIENTE WITH NO DATA;
CREATE TABLE STG_PROMOCOES AS SELECT * FROM DIM_VENDA_PROMOCAO WITH NO DATA;


CREATE TABLE STG_VENDAS( 
        SK_DATA VARCHAR(60) NOT NULL, 
        DT_EMISSAO DATE,
        NK_CLIENTE INTEGER NOT NULL, 
        NK_VENDEDOR INTEGER NOT NULL, 
        NK_PROMOCAO INTEGER NOT NULL, 
        NK_PRODUTO INTEGER NOT NULL, 
        NK_LOJA INTEGER NOT NULL, 
        DD_NOTA_FISCAL DECIMAL NOT NULL, 
        QTD_VENDIDA DECIMAL, 
        VL_PRECO_UNITARIO DECIMAL, 
        VL_TOTAL_PRECO DECIMAL);