CREATE TABLE STG_T_SV_UNIDADE_MEDIDA AS SELECT * FROM T_SV_UNIDADE_MEDIDA WHERE ROWNUM < 1;
CREATE TABLE STG_T_SV_PRODUTO AS SELECT * FROM T_SV_PRODUTO WHERE ROWNUM < 1;
CREATE TABLE STG_T_SV_CLASSIFICACAO_FISCAL AS SELECT * FROM T_SV_CLASSIFICACAO_FISCAL WHERE ROWNUM < 1;
CREATE TABLE STG_T_SV_NOTA_FISCAL AS SELECT * FROM T_SV_NOTA_FISCAL WHERE ROWNUM < 1;
CREATE TABLE STG_T_SV_ITEM_NOTA_FISCAL AS SELECT * FROM T_SV_ITEM_NOTA_FISCAL WHERE ROWNUM < 1;
CREATE TABLE STG_T_SV_FUNCIONARIO AS SELECT * FROM T_SV_FUNCIONARIO WHERE ROWNUM < 1;
CREATE TABLE STG_T_SV_LOJA AS SELECT * FROM T_SV_LOJA WHERE ROWNUM < 1;
CREATE TABLE STG_T_SV_CLIENTE AS SELECT * FROM T_SV_CLIENTE WHERE ROWNUM < 1;
CREATE TABLE STG_T_SV_TIPO_CLIENTE AS SELECT * FROM T_SV_TIPO_CLIENTE WHERE ROWNUM < 1;
CREATE TABLE STG_T_SV_UF AS SELECT * FROM T_SV_UF WHERE ROWNUM < 1;
CREATE TABLE STG_T_SV_CIDADE AS SELECT * FROM T_SV_CIDADE WHERE ROWNUM < 1;
CREATE TABLE STG_T_SV_LOGRADOURO AS SELECT * FROM T_SV_LOGRADOURO WHERE ROWNUM < 1;
CREATE TABLE STG_T_SV_ENDERECO AS SELECT * FROM T_SV_ENDERECO WHERE ROWNUM < 1;

CREATE TABLE STG_ARQ_PROMOCOES (
    CD_PROMOCAO   NUMBER(6) PRIMARY KEY,
    NM_PROMOCAO   VARCHAR2(40),
    DS_PROMOCAO   VARCHAR2(100)
);

CREATE TABLE STG_ARQ_PROMOCOES_OBS (
    CD_PROMOCAO_OBS   NUMBER(6) PRIMARY KEY,
    CD_PROMOCAO       NUMBER(6) NOT NULL,
    OBS_NEGOCIO       VARCHAR2(100)
);