CREATE TABLE STG_T_SV_UNIDADE_MEDIDA AS SELECT * FROM T_SV_UNIDADE_MEDIDA WITH NO DATA;
CREATE TABLE STG_T_SV_PRODUTO AS SELECT * FROM T_SV_PRODUTO WITH NO DATA;
CREATE TABLE STG_T_SV_CLASSIFICACAO_FISCAL AS SELECT * FROM T_SV_CLASSIFICACAO_FISCAL WITH NO DATA;
CREATE TABLE STG_T_SV_NOTA_FISCAL AS SELECT * FROM T_SV_NOTA_FISCAL WITH NO DATA;
CREATE TABLE STG_T_SV_ITEM_NOTA_FISCAL AS SELECT * FROM T_SV_ITEM_NOTA_FISCAL WITH NO DATA;
CREATE TABLE STG_T_SV_FUNCIONARIO AS SELECT * FROM T_SV_FUNCIONARIO WITH NO DATA;
CREATE TABLE STG_T_SV_LOJA AS SELECT * FROM T_SV_LOJA WITH NO DATA;
CREATE TABLE STG_T_SV_CLIENTE AS SELECT * FROM T_SV_CLIENTE WITH NO DATA;
CREATE TABLE STG_T_SV_TIPO_CLIENTE AS SELECT * FROM T_SV_TIPO_CLIENTE WITH NO DATA;
CREATE TABLE STG_T_SV_UF AS SELECT * FROM T_SV_UF WITH NO DATA;
CREATE TABLE STG_T_SV_CIDADE AS SELECT * FROM T_SV_CIDADE WITH NO DATA;
CREATE TABLE STG_T_SV_LOGRADOURO AS SELECT * FROM T_SV_LOGRADOURO WITH NO DATA;
CREATE TABLE STG_T_SV_ENDERECO AS SELECT * FROM T_SV_ENDERECO WITH NO DATA;

CREATE TABLE STG_ARQ_PROMOCOES (
    CD_PROMOCAO   INTEGER PRIMARY KEY,
    NM_PROMOCAO   VARCHAR(40),
    DS_PROMOCAO   VARCHAR(100)
);

CREATE TABLE STG_ARQ_PROMOCOES_OBS (
    CD_PROMOCAO_OBS   INTEGER PRIMARY KEY,
    CD_PROMOCAO       INTEGER NOT NULL,
    OBS_NEGOCIO       VARCHAR(100)
);