CREATE TABLE STG_PRODUTO AS SELECT * FROM DIM_VENDA_PRODUTO WHERE ROWNUM < 1;
CREATE TABLE STG_LOJA AS SELECT * FROM DIM_VENDA_LOJA WHERE ROWNUM < 1;
CREATE TABLE STG_FUNCIONARIO AS SELECT * FROM DIM_VENDA_VENDEDOR WHERE ROWNUM < 1;
CREATE TABLE STG_CLIENTE AS SELECT * FROM DIM_VENDA_CLIENTE WHERE ROWNUM < 1;
CREATE TABLE STG_PROMOCOES AS SELECT * FROM DIM_VENDA_PROMOCAO WHERE ROWNUM < 1;


CREATE TABLE STG_VENDAS( 
        SK_DATA NUMBER NOT NULL, 
        DT_EMISSAO DATE,
        NK_CLIENTE NUMBER NOT NULL, 
        NK_VENDEDOR NUMBER NOT NULL, 
        NK_PROMOCAO NUMBER NOT NULL, 
        NK_PRODUTO NUMBER NOT NULL, 
        NK_LOJA NUMBER NOT NULL, 
        DD_NOTA_FISCAL NUMBER(6,0) NOT NULL, 
        QTD_VENDIDA NUMBER(3,0), 
        VL_PRECO_UNITARIO NUMBER(6,2), 
        VL_TOTAL_PRECO NUMBER(9,2));