CREATE TABLE DIM_VENDA_CLIENTE (
    SK_CLIENTE      INTEGER NOT NULL,
    NK_CLIENTE      INTEGER,
    NM_CLIENTE      VARCHAR(80),
    DT_NASCIMENTO   DATE,
    DS_SEXO         CHAR(1),
    NM_TIPO         VARCHAR(25),
    DS_TIPO         VARCHAR(60),	
    DTC_INI         DATE,
    DTC_FIM         DATE,
    VERSION         INTEGER
);

ALTER TABLE DIM_VENDA_CLIENTE ADD CONSTRAINT DIM_VENDA_CLIENTE_PK PRIMARY KEY ( SK_CLIENTE );

CREATE TABLE DIM_VENDA_DATA (
    SK_DATA               INT  PRIMARY KEY,
    DATA                  DATE NOT NULL,
    ANO                   SMALLINT NOT NULL,
    MES                   SMALLINT NOT NULL,
    DIA                   SMALLINT NOT NULL,
    DIA_SEMANA            SMALLINT NOT NULL,
    DIA_ANO               SMALLINT NOT NULL,
    ANO_BISSEXTO          CHAR(1) NOT NULL,
    DIA_UTIL              CHAR(1) NOT NULL,
    FIM_SEMANA            CHAR(1) NOT NULL,
    FERIADO               CHAR(1) NOT NULL,
    PRE_FERIADO           CHAR(1) NOT NULL,
    POS_FERIADO           CHAR(1) NOT NULL,
    NOME_FERIADO          VARCHAR(30) NULL,
    NOME_DIA_SEMANA       VARCHAR(15) NOT NULL,
    NOME_DIA_SEMANA_ABREV CHAR(3) NOT NULL,
    NOME_MES              VARCHAR(15) NOT NULL,
    NOME_MES_ABREV        CHAR(3) NOT NULL,
    QUINZENA              SMALLINT NOT NULL,
    BIMESTRE              SMALLINT NOT NULL,
    TRIMESTRE             SMALLINT NOT NULL,
    SEMESTRE              SMALLINT NOT NULL,
    NR_SEMANA_MES         SMALLINT NOT NULL,
    NR_SEMANA_ANO         SMALLINT NOT NULL,
    ESTACAO_ANO           VARCHAR(15) NOT NULL,
    DATA_POR_EXTENSO      VARCHAR(50) NOT NULL,
    EVENTO                VARCHAR(50) NULL
);

CREATE TABLE DIM_VENDA_LOJA (
    SK_LOJA       INTEGER PRIMARY KEY,
    NK_LOJA       INTEGER,
    NM_LOJA       VARCHAR(25),
    DS_LOJA       VARCHAR(80),
    DS_ENDERECO   VARCHAR(120),
    NM_CIDADE     VARCHAR(80),
    SG_UF         CHAR(2),
    DTC_INI       DATE,
    DTC_FIM       DATE,
    VERSION       INTEGER
);

CREATE TABLE DIM_VENDA_PRODUTO (
    SK_PRODUTO          INTEGER PRIMARY KEY,
    NK_PRODUTO          INTEGER,
    NM_PRODUTO          VARCHAR(20),
    DS_PRODUTO          VARCHAR(128),
    NK_UNIDADE_MEDIDA   INTEGER,
    DS_SIGLA            CHAR(3),
    DS_UNIDADE_MEDIDA   VARCHAR(30),
    DTC_INI             DATE,
    DTC_FIM             DATE,
    VERSION             INTEGER
);

CREATE TABLE DIM_VENDA_PROMOCAO (
    SK_PROMOCAO    INTEGER PRIMARY KEY,
    NK_PROMOCAO    INTEGER,
    NM_PROMOCAO    VARCHAR(40),
    DS_PROMOCAO    VARCHAR(100),
    OBS_PROMOCAO   VARCHAR(100),
    DTC_INI        DATE,
    DTC_FIM        DATE,
    VERSION        INTEGER
);

CREATE TABLE DIM_VENDA_VENDEDOR (
    SK_VENDEDOR            INTEGER PRIMARY KEY,
    NK_VENDEDOR            INTEGER,
    NM_VENDEDOR            VARCHAR(60),
    DT_NASCIMENTO          DATE,
    DS_SEXO                CHAR(9),
    DT_CONTRATACAO         DATE,
    CD_FAIXA_BONIFICACAO   INTEGER,
    DS_FAIXA_BONIFICACAO   VARCHAR(50),
    DTC_INI                DATE,
    DTC_FIM                DATE,
    VERSION                INTEGER
);

CREATE TABLE FATO_VENDAS (
    SK_DATA             VARCHAR NOT NULL,
    SK_CLIENTE          INTEGER NOT NULL,
    SK_VENDEDOR         INTEGER NOT NULL,
    SK_PROMOCAO         INTEGER NOT NULL,
    SK_PRODUTO          INTEGER NOT NULL,
    SK_LOJA             INTEGER NOT NULL,
    DD_NOTA_FISCAL      INTEGER NOT NULL,
    QTD_VENDIDA         INTEGER,
    VL_PRECO_UNITARIO   DECIMAL,
    VL_TOTAL_PRECO      DECIMAL
);

ALTER TABLE FATO_VENDAS ADD CONSTRAINT FATO_VENDAS_PK PRIMARY KEY ( SK_VENDEDOR,SK_PRODUTO, SK_PROMOCAO, SK_DATA, DD_NOTA_FISCAL, SK_CLIENTE, SK_LOJA );

ALTER TABLE FATO_VENDAS ADD CONSTRAINT FAT_VENDAS_CLIENTE_FK FOREIGN KEY ( SK_CLIENTE )
    REFERENCES DIM_VENDA_CLIENTE ( SK_CLIENTE );

ALTER TABLE FATO_VENDAS ADD CONSTRAINT FAT_VENDAS_DATA_FK FOREIGN KEY ( SK_DATA )
    REFERENCES DIM_VENDA_DATA ( SK_DATA );

ALTER TABLE FATO_VENDAS ADD CONSTRAINT FAT_VENDAS_LOJA_FK FOREIGN KEY ( SK_LOJA )
    REFERENCES DIM_VENDA_LOJA ( SK_LOJA );

ALTER TABLE FATO_VENDAS ADD CONSTRAINT FAT_VENDAS_PRODUTO_FK FOREIGN KEY ( SK_PRODUTO )
    REFERENCES DIM_VENDA_PRODUTO ( SK_PRODUTO );

ALTER TABLE FATO_VENDAS ADD CONSTRAINT FAT_VENDAS_PROMOCAO_FK FOREIGN KEY ( SK_PROMOCAO )
    REFERENCES DIM_VENDA_PROMOCAO ( SK_PROMOCAO );

ALTER TABLE FATO_VENDAS ADD CONSTRAINT FAT_VENDAS_VENDEDOR_FK FOREIGN KEY ( SK_VENDEDOR )
    REFERENCES DIM_VENDA_VENDEDOR ( SK_VENDEDOR );